services:
  random_image:
    image: 'random_image:local'
    container_name: random_image
    volumes:
      - 'your_path_to_images:/app/images'
    ports:
      - '8080:8080'
    restart: unless-stopped